### ISSUE TITLE
How to get the official experimental data

### ISSUE THREAD

**Issue by dt9640214** [caoyunkang/CDO#2]
I used the parameters you provided to train MVTec2D
and the **i_roc** I got is enough high, but the **p_roc** and **p_pro** are about 80 and 60 
(according to different categories, some are even only 40 and 20)
and **p_pro** represents the AU-PRO you announced ? 
Or can AU-PRO get in other ways?

**Comment by caoyunkang** [comment]
Hi! Could you share your experimental categories and your training parameters? I could help to check it.

**Comment by dt9640214** [comment]
抱歉，我发现可能是我在做其他测试的时候不小心改到程式码
我用重新下载的程式码跑之后数据正常了
不过我想确认程式中的：
**i_roc**对应期刊中的**AU-ROC**
**p_roc**没有对应
**p_pro**对应期刊中的**AU-PRO**
这样理解对吗？
