### ISSUE TITLE
怎么对score设阈值来定位缺陷区域

### ISSUE THREAD

**Issue by zq130320339** [caoyunkang/CDO#3]
你好 得到score后，怎么确定缺陷的阈值

**Comment by caoyunkang** [comment]
Hi! You can set the segmentation threshold via the max F1 score criteria. Or you may try to set a threshold manually. The anomaly score distribution in the result directory 'result/<exp_name>/imgs' may be beneficial to manual selection. Thanks!

**Comment by zq130320339** [comment]
好的 谢谢
